
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "temperatura", targetNamespace = "http://controle/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Temperatura {


    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fahparaCel", targetNamespace = "http://controle/", className = "cliente.FahparaCel")
    @ResponseWrapper(localName = "fahparaCelResponse", targetNamespace = "http://controle/", className = "cliente.FahparaCelResponse")
    @Action(input = "http://controle/temperatura/fahparaCelRequest", output = "http://controle/temperatura/fahparaCelResponse")
    public float fahparaCel(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "celparaFah", targetNamespace = "http://controle/", className = "cliente.CelparaFah")
    @ResponseWrapper(localName = "celparaFahResponse", targetNamespace = "http://controle/", className = "cliente.CelparaFahResponse")
    @Action(input = "http://controle/temperatura/celparaFahRequest", output = "http://controle/temperatura/celparaFahResponse")
    public float celparaFah(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0);

}
